# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-04 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strava',
            name='city',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strava',
            name='country',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='strava',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='strava',
            name='longitude',
            field=models.TextField(null=True),
        ),
    ]
