# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0002_auto_20170804_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='strava',
            name='is_stationary_trainer',
            field=models.BooleanField(default=False),
        ),
    ]
