# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-09 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strava', '0003_strava_is_stationary_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='strava',
            name='photo_count',
            field=models.IntegerField(default=0),
        ),
    ]
