# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strava',
            fields=[
                ('activity_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('_date', models.DateField()),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('avg_power', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('moving_time_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('elapsed_time_seconds', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('kudos_count', models.IntegerField(blank=True, null=True)),
                ('elevation_feet', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('kilojoules', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
        ),
    ]
